name: icn
channels:
- defaults
- conda-forge
dependencies:
- python>=3.5
- pip
- mkl
- numpy
- scipy
- matplotlib
- numba
- pyqt>=5.9
- pandas>=0.18
- xlrd
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- pytest
- pytest-cov
- pytest-mock
- pytest-timeout
- joblib
- psutil
- flake8
- spyder
- numexpr
- traits>=4.6.0
- pyface>=6
- traitsui>=6
- mne
- mayavi
- PySurfer
- dipy
- nibabel
- nilearn
- codespell
- python-picard
- simplejson
- pytest-faulthandler
- pytest-sugar
- pydocstyle
- pip:
  - mne_bids
  - autoreject
  - neo
  - pybv